name: CI/CD - Despliegue en Arch Linux

on:
  push:
    branches:
      - main

jobs:
  desplegar-en-local:
    runs-on: self-hosted

    steps:
      - name: Descargar el código nuevo
        uses: actions/checkout@v4

      - name: Construir la nueva imagen de Docker localmente
        run: docker build -t app-palindrome:latest .

      - name: Borrar el contenedor viejo (si existe)
        run: docker rm -f mi-front-end || true

      - name: Levantar la nueva versión actualizada
        run: docker run -d -p 8080:80 --name mi-front-end app-palindrome:latest
